# Generated by Django 6.0.6 on 2026-07-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='place',
            name='address',
        ),
        migrations.RemoveField(
            model_name='place',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='place',
            name='base_rating',
        ),
        migrations.RemoveField(
            model_name='place',
            name='description',
        ),
        migrations.RemoveField(
            model_name='place',
            name='working_hours',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
