# Generated by Django 6.0.6 on 2026-08-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_uz', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_uz', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('counter', 'Counter'), ('boolean', 'Checkbox'), ('text', 'Text Input'), ('select', 'Dropdown Select')], default='counter', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Characteristic',
                'verbose_name_plural': 'Characteristics',
            },
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='amenities_schema',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='characteristics_schema',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='subcategories', to='places.amenity'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='characteristics',
            field=models.ManyToManyField(blank=True, related_name='subcategories', to='places.characteristic'),
        ),
    ]
