# Generated by Django 6.0.6 on 2026-08-18 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_amenity_characteristic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_uz', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('boolean', 'Checkbox (Да/Нет)'), ('counter', 'Counter (Число)'), ('text', 'Text Input (Текст)'), ('select', 'Dropdown Select (Список)')], default='boolean', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
                'ordering': ['group__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ParameterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_uz', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Parameter Group',
                'verbose_name_plural': 'Parameter Groups',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='parameters',
            field=models.ManyToManyField(blank=True, related_name='subcategories', to='places.parameter'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='places.parametergroup'),
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.DeleteModel(
            name='Characteristic',
        ),
    ]
