# Generated by Django 6.0.6 on 2026-08-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_parameter_parametergroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Additional config for specific types (e.g. min, max, unit for counter; options for select)'),
        ),
    ]
