# Generated by Django 6.0.6 on 2026-08-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_parameter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='type',
            field=models.CharField(choices=[('boolean', 'Checkbox (Да/Нет)'), ('counter', 'Counter (Число)'), ('select', 'Dropdown Select (Список)')], default='boolean', max_length=20),
        ),
    ]
