# Generated by Django 6.0.6 on 2026-08-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_parameter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='booking_type',
            field=models.CharField(choices=[('instant', 'Instant Booking'), ('request', 'By Request')], default='request', max_length=50),
        ),
        migrations.AddField(
            model_name='place',
            name='prices',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed prices e.g. {"soatlik": 50000, "kunlik": 400000}'),
        ),
    ]
