# Generated by Django 6.0.6 on 2026-08-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_place_booking_type_place_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('description_ru', models.TextField(blank=True)),
                ('percent', models.PositiveIntegerField()),
                ('discount_type', models.CharField(choices=[('new_listing', 'New Listing Promo'), ('last_minute', 'Last Minute Discount'), ('weekly', 'Weekly Discount'), ('monthly', 'Monthly Discount'), ('custom', 'Custom Discount')], default='new_listing', max_length=50)),
                ('applicable_to', models.CharField(choices=[('all', 'All Categories'), ('specific', 'Specific Categories')], default='all', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('min_nights', models.PositiveIntegerField(blank=True, null=True)),
                ('max_bookings', models.PositiveIntegerField(blank=True, null=True)),
                ('days_before', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='discounts', to='places.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
