# Generated by Django 6.0.6 on 2026-08-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Ключ контента')),
                ('value_ru', models.TextField(blank=True, verbose_name='Текст (RU)')),
                ('value_uz', models.TextField(blank=True, verbose_name='Текст (UZ)')),
            ],
            options={
                'verbose_name': 'Контент сайта',
                'verbose_name_plural': 'Контент сайта',
            },
        ),
    ]
