# Generated by Django 6.0.6 on 2026-08-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0003_tariffplan_tariffsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffplan',
            name='features_en',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='features_ru',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
