# Generated by Django 6.0.6 on 2026-08-14 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0003_tariffplan_tariffsubscription'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tariffs.tariffplan'),
        ),
        migrations.AddField(
            model_name='user',
            name='tariff_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('partner', 'Partner (Club Owner)'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
